### ISSUE TITLE
Replication slowly desync after 48h

### ISSUE THREAD

**Issue by jrm2194** [couchbaselabs/elasticsearch-transport-couchbase#102]
We are using 
* ElasticSearch 1.7.2
* Couchbase 4.0 GA
* Transport Plugin 2.1

2 CB buckets replicating to 2 ES indexes. Our biggest bucket (users) has 200,000 objects and is growing by 5,000 objects per day.

The replication seems to work fine for roughly 48 hours... After 48-72 hours, ES needs few seconds to sync... After few days, ES needs sometimes up to 20 minutes to catch up on CB.

The only way to fix it: Dump ALL DATA from ES, recreate the index, re-index everything from scratch.

There is nothing in the logs (Either the goxdcr logs or the ES logs).

Anybody ran into the same issues?

Thank you,

Jean

**Comment by chester89** [comment]
We have same setup (Couchbase 4.0 + ElasticSearch 1.7.x) with 2.1 plugin version. I didn't notice any issues you mention. Our buckets are of different sizes. What OS and JVM version do you use?

**Comment by jrm2194** [comment]
Hi Chester,

Thank you for taking the time to reply. 
ES is running on Ubuntu 14.04 and java version "1.8.0_60"

Our ES cluster is only made of 3 nodes (1 master and 2 data). I'm not sure if that's related to our problem.

Jean

**Comment by mschoch** [comment]
As a first step, we need to get log output.  Please find modify your config/logging.yml on all nodes to include the following (must be in the LOGGER section):

transport.couchbase: TRACE
com.couchbase: TRACE

At this level, there should be something, even if nothing is going wrong on this side.  Second, do you see anything in the xdcr.log or xdcr-error.log?  (these files may have gone away as I have not done testing with 4.0 yet.

Also, there is known issue with Couchbase 4.0 with Elasticsearch adapter, while it does not specifically relate to it not working after 48 hours, the fact that the CPU gets stuck high could be related.  See https://issues.couchbase.com/browse/MB-16244

**Comment by WillGardella** [comment]
The issue Marty mentioned (MB-16244) is resolved in the Couchbase Server 4.1 Dev Preview, if you want to try the fix.

**Comment by jrm2194** [comment]
Thank you guys!

We are going to add some traces logs. We were monitoring our CPU and never had a problem with it in the past 2 months. 

It has to be something else... Even if we delete the "delayed" ES index et recreate it, we still have the problem. The only way to fix it is to wipe out the entire ES data and recreate ALL indexes from scratch.

**Comment by jrm2194** [comment]
Alright... It's happening again (after 10 days this time).

Nothing weird in the logs despite the trace mode:
```
[2015-11-23 06:55:56,585][TRACE][transport.couchbase.capi ] [node1] ignoreDelete = false
[2015-11-23 06:55:56,585][TRACE][transport.couchbase.capi ] [node1] Bulk doc entry is [{base64=eyJpZCI6IkVBMTkzMDY2IiwidG9rZW4iOiI1NTdmN2YzNWE4MDBmMzg2MDFiNmU4NzQ3MjlkYTU4NGNhYWI3NmJlZDdlZTU0MDYiLCJsb2NhdGlvbiI6eyJsYXQiOjQ1Ljc3OTc5OTM3ODQ2OTQxLCJsb24iOjMuMTAwNTc2MTk5OTcyNzQzfSwibG9jYXRpb25fZm9yY2VkIjpudWxsLCJlbWFpbCI6IjE5ODc2MDI4NzEyMTYzMUBvbmNlbWFpbC5tZSIsImZpcnN0X25hbWUiOiJUaMOpbyIsImxhc3RfbmFtZSI6Ik1hc3NvbiIsImJpcnRoZGF5IjoiMTk5Ni0wNy0xNCIsImFnZSI6MTksImdlbmRlciI6Im0iLCJpbnRlcmVzdGVkX2luIjoidyIsImV0aG5pY2l0eSI6WyJ3Il0sImV0aG5pY2l0eV9jaG9zZW4iOltdLCJoZWlnaHQiOjE3OCwibGFuZ3VhZ2VzIjpbImZyIl0sInJlbGlnaW9uIjoiYXRoIiwiZmFjZWJvb2tfaWQiOiIxOTg3NjAyODcxMjE2MzEiLCJmYWNlYm9va19mcmllbmRzIjpbXSwiZmFjZWJvb2tfZnJpZW5kc19jb3VudCI6MCwic2lnbnVwIjpmYWxzZSwicGljdHVyZXMiOlsiMTE1MDM2NCIsIjExNTM4MDEiLCIxMTUzODA4Il0sInBpY3R1cmVzX3RtcCI6W10sInJhdGluZyI6MywiZWR1Y2F0aW9uIjpbXSwiZWR1Y2F0aW9uX2xldmVsIjpudWxsLCJzb2NpYWxfY2xhc3MiOjIsInN0eWxlIjpbXSwib2NjdXBhdGlvbiI6eyJlbXBsb3llciI6bnVsbCwicG9zaXRpb24iOm51bGx9LCJwaG9uZSI6IiszMzYyODE4MTMwOSIsInBob25lX3ZlcmlmaWVkIjp0cnVlLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInBpY3R1cmVfdmVyaWZpZWQiOnRydWUsIm1vZGVyYXRpb25fcXVldWUiOnRydWUsImxhc3RfcGljdHVyZV91cGRhdGVkX2F0IjoxNDQ3ODQ5NjQyLCJsb2NhdGlvbl9uYW1lIjoiQ2xlcm1vbnQtRmVycmFuZCIsInRpbWV6b25lIjoiRXVyb3BlL1BhcmlzIiwiY291bnRyeV9jb2RlIjoiRlIiLCJiYW5uZWQiOmZhbHNlLCJkZWxldGVkIjpmYWxzZSwiZGlzYWJsZWQiOmZhbHNlLCJjcmVhdGVkX2F0IjoxNDQ3ODIzOTgwLCJ1cGRhdGVkX2F0IjoxNDQ4Mjc5NzU3LCJsYXN0X29ubGluZSI6MTQ0ODI3OTc0NCwibWF0Y2hfc2V0dGluZ3MiOnsiZGlzdGFuY2UiOjMwLCJldGhuaWNpdHkiOltdLCJyZWxpZ2lvbiI6W10sImFnZV9taW4iOjE3LCJhZ2VfbWF4IjoyM30sIm1hdGNoX2lkIjoiTUVBMjU5MjA3MyIsInNlY29uZF9tYXRjaF9pZCI6bnVsbCwiaGlkZGVuX21hdGNoX2lkIjpudWxsLCJoaWRkZW5fbWF0Y2hfYXQiOjAsIm5leHRfbWF0Y2hfaWQiOm51bGwsIm5leHRfc2Vjb25kX21hdGNoX2lkIjpudWxsLCJ3YWl0bGlzdF9zaXplIjowLCJ3YWl0bGlzdF9maXJzdCI6bnVsbCwibG9jYWxlIjoiZnIiLCJsYXN0X2RldmljZSI6eyJhbmRyb2lkIjpudWxsLCJpb3MiOjE0NDgyNzk3NTcsIndlYiI6bnVsbH0sImFwcF92ZXJzaW9uIjp7ImFuZHJvaWQiOm51bGwsImlvcyI6bnVsbCwid2ViIjpudWxsfSwid2FsbGV0IjowLCJzdWJzY3JpYmVyIjpmYWxzZSwidHJhY2tpbmciOnsibmV0d29yayI6Im9yZ2FuaWMiLCJjYW1wYWlnbiI6bnVsbH0sImludml0ZWRfYnkiOm51bGwsImhhc19yYXRlZCI6ZmFsc2V9, meta={expiration=0, flags=0, id=user::EA193066, rev=738-141952c3de9200000000000000000000}}][2015-11-23 06:55:56,585][TRACE][transport.couchbase.capi ] [node1] Selecting type couchbaseDocument for document user::EA193066 in index users[2015-11-23 06:55:56,590][INFO ][transport.couchbase.capi ] [node1] bulk index succeeded after 1 tries
[2015-11-23 06:55:56,621][DEBUG][transport.couchbase.capi ] [node1] no uuid in database name
[2015-11-23 06:55:56,621][TRACE][com.couchbase.capi.servlet.CAPIServlet] Got revs diff request for users/916
[2015-11-23 06:55:56,621][TRACE][com.couchbase.capi.servlet.CAPIServlet] revs diff request body was {"user::EA126946":"594-141952c3e78700000000000000000000"}
[2015-11-23 06:55:56,621][TRACE][com.couchbase.capi.servlet.CAPIServlet] revs diff parsed value is {user::EA126946=594-141952c3e78700000000000000000000}
[2015-11-23 06:55:56,621][TRACE][transport.couchbase.capi ] [node1] _revs_diff request for users/916 : {user::EA126946=594-141952c3e78700000000000000000000}
[2015-11-23 06:55:56,621][TRACE][transport.couchbase.capi ] [node1] _revs_diff response for users/916 is: {user::EA126946={missing=594-141952c3e78700000000000000000000}}
[2015-11-23 06:55:56,622][TRACE][transport.couchbase.capi ] [node1] _revs_diff response AFTER conflict resolution {user::EA126946={missing=594-141952c3e78700000000000000000000}}
[2015-11-23 06:55:56,662][DEBUG][transport.couchbase.capi ] [node1] no uuid in database name
[2015-11-23 06:55:56,662][TRACE][com.couchbase.capi.servlet.CAPIServlet] Got revs diff request for users/766
[2015-11-23 06:55:56,662][TRACE][com.couchbase.capi.servlet.CAPIServlet] revs diff request body was {"user::EA54429":"1908-141952c3e5de00000000000000000000"}
[2015-11-23 06:55:56,662][TRACE][com.couchbase.capi.servlet.CAPIServlet] revs diff parsed value is {user::EA54429=1908-141952c3e5de00000000000000000000}
[2015-11-23 06:55:56,663][TRACE][transport.couchbase.capi ] [node1] _revs_diff request for users/766 : {user::EA54429=1908-141952c3e5de00000000000000000000}
[2015-11-23 06:55:56,663][TRACE][transport.couchbase.capi ] [node1] _revs_diff response for users/766 is: {user::EA54429={missing=1908-141952c3e5de00000000000000000000}}
[2015-11-23 06:55:56,664][TRACE][transport.couchbase.capi ] [node1] _revs_diff response AFTER conflict resolution {user::EA54429={missing=1908-141952c3e5de00000000000000000000}}
[2015-11-23 06:55:56,693][DEBUG][transport.couchbase.capi ] [node1] no uuid in database name
[2015-11-23 06:55:56,693][TRACE][com.couchbase.capi.servlet.CAPIServlet] Got bulk docs request for users/916
[2015-11-23 06:55:56,725][DEBUG][transport.couchbase.capi ] [node1] no uuid in database name
```

**Comment by WillGardella** [comment]
Hi Jean,
Do I understand correctly that it was running fine for about 10 days and then suddenly started to slow down, or has the indexing performance been slowing down steadily over the course of the 11 days?

Do your ES nodes index anything independent of Couchbase, or handle any other workload? I'm assuming the answer is no but just want to make sure that it's not the ES grinding to a halt on its own.

**Comment by jrm2194** [comment]
Hi Will,

It suddenly started to slow down... In only few minutes the replication was a dozen items behind... then a few hundreds. Recreating the index didn't solve the problem. We had to wipe out ALL Elasticsearch data on every single node to fix it.

Our ES nodes are ONLY indexing Couchbase.

**Comment by android-programmer** [comment]
I also experienced the same problem.
2 couchbase 4.0  nodes -> 3 elasticsearch 1.7.2  nodes.   AMI 

bucket 1: 400m documents
bucket 2:100m documents  

in ES index, they only have 500 thousands documents after 1 day of replication

**Comment by android-programmer** [comment]
8 couchbase 3.0.x nodes -> 3 elasticsearch 1.7.2 nodes. AMI

bucket 1: 400m documents
bucket 2:100m documents

in ES index, they only have 500 thousands documents after 1 day of replication

**Comment by Branor** [comment]
This ticket is pretty old at this point. if you're still having this issue, please open a new one. The important bits of information to diagnose it would be the ES log (any errors from ES or the plugin) and the Couchbase xdcr_errors log.
